# Generated by Django 3.1.7 on 2021-03-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Welfare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='', max_length=15)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
